(Chore) Document the process for importing new data
UKGovernmentBEIS/beis-report-official-development-assistance pull request #1044
Opened 2021-03-31 16:05 UTC by mec

When we on-board new delivery partners we need to bring in all their
existing activities and financial data at the time they are on-boarded.

This is a one time only operation run by developers with data supplied
by BEIS.

We want to document the process in the code as the most useful place to
do so and expect it to be removed once the service completes on-boarding
all delivery partners in Q1 2021-2022.

2021-04-12 10:24 UTC, robbiepaul approved these changes
LGTM

2021-04-12 16:40 UTC, CristinaRO requested changes
We've made some changes to the activity import process that need to be reflected in the documentation.

2021-04-12 16:40 UTC, CristinaRO commented on doc/importing-new-delivery-partner-data.md
> +cd /app && /usr/local/bin/ruby bin/rails activities:import CSV=FILENAME ORGANISATION_ID=ORGANISATION_ID
We have now added the requirement to provide the email of the uploader to the task: https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/pull/1058/commits/6af9d88a21bd4234ca894b5b3fe7a06c834f990c.

The uploader is then passed to the `ImportFromCsv` service and used to determine the permissions of the uploader via the organisation that they belong to, so you might want to make it clearer in the instructions that the uploader will have to change their account to belong to the correct organisation for the task they're running.

2021-04-14 10:51 UTC, CristinaRO approved these changes

2021-04-14 11:24 UTC, merged