(1823) Make some changes to how budgets work in the application
UKGovernmentBEIS/beis-report-official-development-assistance pull request #1192
Opened 2021-06-18 14:05 UTC by pezholio

This makes the following changes to budgets: 

* Transfers are removed as budget types
* `External non Official Development Assistance` removed as a budget type
* `External Official Development Assistance` budget type changed to `Other official development assistance`
*  The Direct (Newton Fund) and Direct (Global Challenges Research Fund) types have been replaced with one `Direct` budget type.

⚠️ There is also a data migration to be run once this code hits production ⚠️ 

## Screenshots

### Before

![image](https://user-images.githubusercontent.com/109774/122572255-79388480-d045-11eb-9d53-579c33486f2a.png)

### After

![image](https://user-images.githubusercontent.com/109774/122572313-8786a080-d045-11eb-9570-a8a2a6cc8f44.png)

2021-06-18 14:05 UTC, pezholio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make some changes to how Budgets work in the application](https://trello.com/c/Kn1pKEl4/1823-make-some-changes-to-how-budgets-work-in-the-application)

2021-06-21 17:01 UTC, CristinaRO requested changes
Given the recent issues we've had with other enum radio button types not being preserved on edit, I'd feel more confident if "user can edit a budget" was also testing that editing an external budget shows the existing selection of an external budget and the providing org.

2021-06-22 12:51 UTC, pezholio commented on db/schema.rb
> -    t.string "intended_beneficiaries", array: true
Yeah, sorry. I'm normally so careful with this!

2021-06-22 14:11 UTC, CristinaRO approved these changes
Thank you!

2021-06-22 14:11 UTC, merged