(2123) Users can export budget data
UKGovernmentBEIS/beis-report-official-development-assistance pull request #1348
Opened 2021-09-16 09:24 UTC by pezholio

This allows users to export data about budgets. BEIS users can export budgets for all activities, or specific organisations, while DPs can export data for their own organisation.

# Screenshots

## Export page

![image](https://user-images.githubusercontent.com/109774/133586804-b2ace794-b6c2-4d06-a445-0ce7d2793c9e.png)

## Organisation export page (BEIS user)

![image](https://user-images.githubusercontent.com/109774/133586850-9dafa734-e719-4447-ba30-55dbecc1f9c1.png)

## Organisation export page (Delivery partner)

![image](https://user-images.githubusercontent.com/109774/133586977-7ab2013f-7dd0-4c48-a2dc-05971dde158c.png)

2021-09-16 09:27 UTC, pezholio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users can export budget data](https://trello.com/c/SNpQakMp/2123-users-can-export-budget-data)

2021-09-16 14:10 UTC, mec commented
@pezholio this is totally my fault: could we add the Delivery partner organisation name to the columns in the file? Ideally only on the one that exports all delivery partner data, but if it's in both it is not a problem. It can go in after `Delivery partner identifier` (column C).

This is so a BEIS user can sort and filter the data by delivery partner without relying on the RODA identifier, which can be problematic.

2021-09-16 15:50 UTC, mec requested changes
I've looked this over and poked it in the app - it is shapping up super nicely.

I do feel like there is something amiss though, I was expecting to see:

- multiple rows where an activity has multiple budgets for the same financial year
- level B (programme) budgets should be in the org specific file, I think this is our old friend the many organisation roles again

Happy to have chat about this if helpful, just let me know?

2021-09-16 15:50 UTC, mec commented on app/controllers/staff/exports/organisations_controller.rb
> +        export = Actual::Export.new(activities)
Thank you for doing this - a great start to a PR - make thing better! 👍

2021-09-20 10:37 UTC, pezholio commented on app/models/financial_year.rb
> +  def pred
This is an internal Ruby thing, that makes the class iterable. There's a test in the FinancialYear spec

2021-09-20 10:38 UTC, pezholio commented on app/models/financial_year.rb
> +  def pred
I'll edit the commit message - I agree though, `pred` does sound better!

2021-09-21 09:31 UTC, mec approved these changes

2021-09-21 09:51 UTC, merged