Fix: 16160 - Bulk update of activities including implementing organisations
UKGovernmentBEIS/beis-report-official-development-assistance pull request #1696
Opened 2022-06-13 08:00 UTC by edavey

## Summary

This PR fixes two bugs in the handling of implementing organisations when updating activities using the bulk upload method:

1. the bulk upload CSV template for activities was missing a column for describing each activity's implementing organisations. This resulted in any pre-existing associations being removed when an activity was updated in this way. We now have a `Implementing organisation names` column which takes a pipe-delimited list of organisation names
2. the update code (in `Activity::ImportFromCsv`) did not handle an activity being associated with multiple implementing organisations. 

## Details

This work results from a [bug report 16160](https://dxw.zendesk.com/agent/tickets/16160) showing that whenever an
activity with a pre-existing implementing organisation
association is updated via the bulk upload CSV mechanism,
the activity was stripped of its implementing organisations.

However, it makes sense that any pre-existing implementing organisation associations
which are not present in an update should be removed when the update is
applied. e.g.:

**pre-existing state:**
implementing orgs = [Org A, Org B]

**desired post-update state:**
implementing orgs = [Org A, Org C]

In the bulk upload CSV for the update, in column "Implementing organisation names",
I should expect to find: "Org A | Org C".

i.e. any implementing orgs not present in the update will be removed and any orgs
which are not present on the activity will be added.

### The fix

Multiple implementing orgs are now supplied in pipe-delimited
form, e.g. under the column "Implementing organisation names"
I can list:

```
Existing Org | Additional Org 1 | Additional Org 2
```

(NB: whitespace around the pipe is not signficant)

If one or more of the given organisation names does not
match up with a pre-defined organisation (that organisation
has not been set up in RODA) then I will be shown an error
message identifying the problem organisation(s), e.g.

"Additional Org 1 | Additional Org 2 is/are not a known implementing organisation(s)"

Error handling when 2 unknown implementing organisations are supplied in the CSV:

<img width="1173" alt="error_handling" src="https://user-images.githubusercontent.com/20245/173305274-8b7df645-97ff-41ed-911d-93c4044c4f2f.png">

### We will need guidance for delivery partners

We need *guidance* to let DPs know that failure to provide this
implementing organisation information will be destructive,
i.e. if they don't re-supply all the implementing orgs which
should be associated with an activity, then any associations
will be removed as part of the update.

## Next steps

- [x ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.

2022-06-15 15:59 UTC, dragon-dxw commented
Does the CSV template pre-populate the pipe-separated implementing organisations? Can't see any code that looks like that, which would go a long way towards being less destructive (unless deliberate)...

It's possible I've missed it.

2022-06-15 16:43 UTC, edavey commented
> Does the CSV template pre-populate the pipe-separated implementing organisations? Can't see any code that looks like that, which would go a long way towards being less destructive (unless deliberate)...
> 
> It's possible I've missed it.

thanks @dragon-dxw good point! 

I wasn't aware that the Activities bulk upload CSV "template" which is offered as a download could contain activity rows as well as an initial headers row. But looking at the code it's plain that "reportable activities" are included:

https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/1e382c87d9af0d05a81fc9920ce149869808619f/app/controllers/staff/actual_uploads_controller.rb#L19-L30

I'll take another run at this. Thanks!

2022-06-16 11:44 UTC, dragon-dxw requested changes
As per the comments, the CSV template should be pre-populated with the pipe-separated implementing organisations. Otherwise very happy with everything else.

2022-06-22 09:15 UTC, dragon-dxw approved these changes
I see this commit as resolving half the problem -- this enables users to bulk update and not erase all implementing orgs for an activity, if they type in the data manually, which is a significant step up from always erasing all implementing orgs for an activity.

It's not complete -- a complete handling would provide the implementing orgs in the activities template -- but it is a marked improvement on the current situation and provides excellent groundwork for a later PR which just populates that field in the template.

2022-06-22 09:19 UTC, merged