Chore/update terraform docs
UKGovernmentBEIS/beis-report-official-development-assistance pull request #997
Opened 2021-03-16 17:04 UTC by jcoglan

## Changes in this PR

## Screenshots of UI changes

### Before

### After

## Next steps

- [ ] Is an ADR required? An ADR should be added if this PR introduces a change to the architecture.
- [ ] Is a changelog entry required? An entry should always be made in `CHANGELOG.md`, unless this PR is a small tweak which has no impact outside the development team.
- [ ] Do any environment variables need amending or adding?
- [ ] Have any changes to the XML been checked with the IATI validator? See [XML Validation](https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/xml-validation.md)

2021-03-17 09:16 UTC, mec requested changes
This is so much better. Thank you for taking the time to do this. I left two comments I think we should address.

2021-03-17 09:16 UTC, mec commented on terraform/README.md
> +We should avoid manual deployments but the following instructions will allow you
Could we change this to account for the fact we have to manually deploy the training/pentest environment? Perhaps somehting like:

> We avoid manual deployments on production and staging, but require them on our training environment (pentest).

2021-03-17 09:16 UTC, mec commented on terraform/README.md
> +
Could we add somehitng here like 'Never commit sensitive information like keys, secrets or passwords'?

2021-03-17 16:59 UTC, jcoglan commented
@mec I've made the changes you requested now.

2021-03-18 08:57 UTC, mec approved these changes
🚢

2021-03-18 08:57 UTC, mec commented
/rebase

2021-03-18 10:03 UTC, pezholio commented
/rebase

2021-03-18 10:15 UTC, merged